# Generated by Django 5.0.4 on 2024-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribesettings',
            name='client',
            field=models.ManyToManyField(blank=True, to='mailing.client', verbose_name='клиент'),
        ),
    ]
