# Generated by Django 5.0.4 on 2024-04-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_subscribesettings_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribesettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='сообщение'),
        ),
    ]
