# Generated by Django 5.0.4 on 2024-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_subscribesettings_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribesettings',
            name='next_run',
            field=models.DateTimeField(default='2024-04-01', verbose_name='дата и время следующей рассылки'),
            preserve_default=False,
        ),
    ]
