# Generated by Django 5.0.4 on 2024-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_subscribesettings_next_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribesettings',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время следующей рассылки'),
        ),
    ]
