# Generated by Django 4.2.2 on 2024-05-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_subscribesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribesettings',
            options={'permissions': [('can_subscribe_off', 'Can subscribe off')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
