# Generated by Django 4.2.2 on 2024-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_subscribesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribesettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность рассылки'),
        ),
    ]
